#!/usr/bin/env bash

if [ -z "${GIT_COMMITTER_DATE:-}" ]
then
  git log --format=%cd --date=unix --max-count=2 | {
    read -r this
    read -r last
    # if [ "$this" -le "$(date +%s --date=9:00:00)" ]
    # then
    #   exit
    # fi
    new="$(date +%s --date=19:00:00)"
    mod=7200
    for item in "$this" "$last"
    do
      if [ "$item" -gt "$new" ]
      then
        new="$item"
        mod=600
      fi
    done
    if [ "$new" != "$this" ]
    then
      new="$((RANDOM % mod + 120 + new))"
      GIT_COMMITTER_DATE="$new" git commit --amend --no-edit --date "$new"
    fi
  }
fi
