#!/usr/bin/env bash

if [ -n "${GIT_COMMITTER_DATE:-}" ]
then
  exit
fi

git log --format=%cd --date=unix --max-count=2 | {
  read -r this
  read -r last

  night="$(date +%s --date=19:00:00)"
  if [ "$this" -gt "$night" ]
  then
    exit
  fi

  new="$((night - 86400))"
  mod=7200
  if [ "$last" -gt "$new" ] && [ "$last" -le "$((night - 68400))" ]
  then
    new="$last"
    mod=600
  fi

  new="$((RANDOM % mod + 120 + new))"
  GIT_COMMITTER_DATE="$new" git commit --amend --no-edit --date "$new"
}
