#!/bin/sh

run() {
  app_id=$1
  shift

  focused=$(swaymsg -t get_tree | jq -r '.. | select(.type?) | select(.focused==true).app_id')
  if [ "$focused" = "$app_id" ]
  then
    swaymsg --quiet '[app_id=firefox]' focus
    wtype -k space
  else
    if [ "$focused" = firefox ]
    then
      wtype -k space
    fi
    swaymsg --quiet "[app_id=$app_id]" focus || {
      dualsensectl trigger right feedback 5 8
      "$@"
    }
  fi
}

if command -v moonlight >/dev/null
then
  run com.moonlight_stream.Moonlight moonlight stream office BotW
else
  run info.cemu.Cemu cemu --fullscreen --title-id 00050000101c9300
fi
