version: 2
updates:
  - package-ecosystem: github-actions
    # https://github.com/dependabot/dependabot-core/issues/6704
    # Need to list every dirs containing the composite `action.yml` file
    directories:
      - /
      - /.github/actions/package
    schedule:
      interval: weekly
