# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/73becaef-0da8-4a61-bec4-77c6557bc543";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/498A-D13D";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home/steamos" =
    { device = "/dev/disk/by-uuid/1bb334e6-3c14-46b3-9bae-d50053587d50";
      fsType = "ext4";
    };

  fileSystems."/home/deck/.local/share/Steam" =
    { device = "/home/steamos/deck/.local/share/Steam";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/home/deck/Games" =
    { device = "/home/steamos/deck/Games";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/home/deck/.local/share/Steam/steamapps/shadercache" =
    { device = "/home/deck/.cache/shadercache";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/home/deck/Installs" =
    { device = "/home/steamos/deck/Installs";
      fsType = "none";
      options = [ "bind" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
