automation:
  - alias: Auto brightness day
    trigger:
      - platform: state
        entity_id: &all_lights
          - light.living_room
          - light.primary_bedroom
          - light.secondary_bedroom
          - light.kids_room
          - light.kitchen_door
          - light.kitchen_window
          - light.bathroom
        to: 'on'
    condition:
      - condition: time
        after: '07:35:00'
        before: '22:45:00'
      - condition: template
        value_template: >-
          {{ state_attr(trigger.entity_id, 'brightness') < 250 }}
    action:
      service: light.turn_on
      data_template:
        entity_id: >-
          {{ trigger.entity_id }}
        brightness: 255

  - alias: Auto brightness night
    trigger:
      - platform: state
        entity_id: *all_lights
        to: 'on'
    condition:
      - condition: time
        after: '22:45:00'
        before: '07:35:00'
      - condition: template
        value_template: >-
          {{ state_attr(trigger.entity_id, 'brightness') > 5 }}
    action:
      service: light.turn_on
      data_template:
        entity_id: >-
          {{ trigger.entity_id }}
        brightness: 1

  - alias: Sync kitchen lights
    trigger:
      - platform: state
        entity_id:
          - light.kitchen_door
          - light.kitchen_window
        to: 'off'
        for: '00:00:01'
    condition:
      condition: state
      entity_id: light.kitchen
      state: 'on'
    action:
      service: light.turn_off
      data:
        entity_id: light.kitchen
