#!/usr/bin/env bash

jj op log --limit 1
echo

revsets=$1
if [ -z "$revsets" ]; then
  revsets=""
  while read -r hour rev; do
    if [ "$hour" -lt 19 ]; then
      revsets="$rev::@"
      break
    fi
  done < <(jj log --no-graph --reversed --template 'committer.timestamp().format("%-H") ++ " " ++ change_id ++ "\n"' --revisions "mutable()::@")
  if [ -z "$revsets" ]; then
    jj log --revisions "mutable()::@"
    echo
    echo "No need to modify"
    exit
  fi
fi

last=$(jj log --color never --no-graph --limit 1 --template 'committer.timestamp().format("%s")' --revisions "roots($revsets)-")

night="$(date +%s --date=19:00:00)"
new="$((night - 86400))"
mod=7200
if [ -n "$last" ] && [ "$last" -gt "$new" ] && [ "$last" -le "$((night - 68400))" ]; then
  new="$last"
  mod=600
fi

while read -r rev same; do
  new="$((RANDOM % mod + 120 + new))"
  timestamp="$(date -Iseconds --date=@"$new")"
  args=()
  if [ "$same" = true ]; then
    args=(--author-timestamp "$timestamp")
  fi
  JJ_TIMESTAMP="$timestamp" jj metaedit --ignore-immutable --force-rewrite "${args[@]}" "$rev"
  mod=600
done < <(jj log --no-graph --reversed --template 'change_id ++ " " ++ author.email() == committer.email() ++ "\n"' --revisions "$revsets")

echo
jj log --revisions "$revsets"
