#!/usr/bin/env bash

finish() {
  echo
  jj log --revisions "${from}-..${to}"
  exit
}

jj op log --limit 1
echo

from=$1
if [ -z "$from" ]; then
  from="immutable_heads()"
fi

to=$2
if [ -z "$to" ]; then
  to="@"
fi

if [ -z "$1" ]; then
  new_from=""
  while read -r hour rev; do
    if [ "$hour" -lt 19 ]; then
      new_from="${rev}-"
      break
    fi
  done < <(jj log --no-graph --reversed --template 'committer.timestamp().format("%-H") ++ " " ++ change_id ++ "\n"' --revisions "${from}..${to}")
  if [ -n "$new_from" ]; then
    from="$new_from"
  else
    finish
  fi
fi

last=$(jj log --color never --no-graph --limit 1 --template 'committer.timestamp().format("%s")' --revisions "roots(${from}..${to})-")

night="$(date +%s --date=19:00:00)"
new="$((night - 86400))"
mod=7200
if [ -n "$last" ] && [ "$last" -gt "$new" ] && [ "$last" -le "$((night - 68400))" ]; then
  new="$last"
  mod=600
fi

while read -r rev email name; do
  new="$((RANDOM % mod + 120 + new))"
  JJ_TIMESTAMP="$(date -Iseconds --date=@"$new")" JJ_USER="$name" JJ_EMAIL="$email" jj describe --reset-author --no-edit --ignore-immutable "$rev"
  mod=600
done < <(jj log --no-graph --reversed --template 'change_id ++ " " ++ author.email() ++ " " ++ author.name() ++ "\n"' --revisions "${from}..${to}")

finish
