underline: &underline {underline: {size: 2, color: 81A1C1FF}}

bar:
  location: top
  height: 26
  background: 2E3440FF
  font: monospace:pixelsize=16
  spacing: 6
  margin: 12

  left:
    - i3:
        anchors:
          - string: &default {text: "{name}", margin: 6, on-click: "@msgcmd@ --quiet workspace {name}"}
          - focused: &focused
              foreground: EBCB8BFF
          - urgent: &urgent
              foreground: 000000FF
              deco: {stack: [background: {color: BF616AFF}]}
        sort: ascending
        content:
          "":
            map:
              default: {string: {<<: *default}}
              conditions:
                state == focused: {string: {<<: [*default, *focused]}}
                state == urgent: {string: {<<: [*default, *urgent]}}

  center:
    - foreign-toplevel:
        content:
          map:
            conditions:
              ~activated: {empty: {}}
              activated:
                - string: {text: "{app-id}"}

  right:
    - script:
        path: @scripts@/netspeed
        content:
          - string: {text: "{rate}"}
    - cpu:
        poll-interval: 10000
        content:
          map:
            conditions:
              id < 0:
                - string: {text: "󰓅", right-margin: 4}
                - string: {text: "{cpu}%"}
    - mem:
        poll-interval: 10000
        content:
          - string: {text: "󰍛", right-margin: 4}
          - string: {text: "{free:gb}G"}
    - pulse:
        content:
          - map:
             conditions:
               sink_muted:
                 - string: {text: "󰖁", right-margin: 4}
               ~sink_muted:
                 - string: {text: "󰕾", right-margin: 4}
          - string: {text: "{sink_percent}"}
    - clock:
        date-format: "%a %m-%d"
        content:
          - string: {text: "", right-margin: 4}
          - string: {text: "{date} {time}"}
