underline: &underline {underline: {size: 2, color: 81A1C1FF}}

bar:
  location: top
  height: 26
  background: 2E3440FF
  font: monospace:pixelsize=16
  spacing: 6
  margin: 12

  left:
    - i3:
        anchors:
          - string: &default {text: "{name}", margin: 6, on-click: "swaymsg --quiet workspace {name}"}
          - focused: &focused
              foreground: EBCB8BFF
          - urgent: &urgent
              foreground: 000000FF
              deco: {stack: [background: {color: BF616AFF}]}
        sort: ascending
        content:
          "":
            map:
              tag: state
              values:
                focused:   {string: {<<: [*default, *focused]}}
                unfocused: {string: {<<: *default}}
                invisible: {string: {<<: *default}}
                urgent:    {string: {<<: [*default, *urgent]}}

  center:
    - foreign-toplevel:
        content:
          map:
            tag: activated
            values:
              false: {empty: {}}
              true:
                - string: {text: "{app-id}"}

  right:
    - script:
        path: @scripts@/net-speed
        content:
          - string: {text: "", right-margin: 6}
          - string: {text: "{rate}"}
    - cpu:
        interval: 10000
        content:
          - string: {text: "龍", right-margin: 2}
          - string: {text: "{cpu}%"}
    - mem:
        interval: 10000
        content:
          - string: {text: "", right-margin: 2}
          - string: {text: "{free:gb}G"}
    - alsa:
        card: default
        mixer: Master
        content:
          - map:
             tag: muted
             values:
               true:
                 - string: {text: "婢", right-margin: 2}
               false:
                 - string: {text: "墳", right-margin: 2}
          - string: {text: "{percent}"}
    - clock:
        date-format: "%a %m-%d"
        content:
          - string: {text: "", right-margin: 2}
          - string: {text: "{date} {time}"}
