#!/usr/bin/env sh

set -u

nix_index_tag="$(curl -fsSL https://api.github.com/repos/Mic92/nix-index-database/releases/latest | awk -F'"' '/"tag_name"/ {print $4}')"
sed -i -e "s|/[0-9-]\{10\}/|/${nix_index_tag}/|" common/nix-index.nix

update_fetchgit() {
  file="$1"
  echo "Update $file"
  nix run nixpkgs#update-nix-fetchgit -- "$file"
  if git commit -m "update-src: Auto update $file" "$file" 1>/dev/null
  then
    git --no-pager show
  fi
}

update_fetchgit common/neovim/nvchad.nix
update_fetchgit common/nix-index.nix
update_fetchgit pkgs/rime-idvel/default.nix
# update_fetchgit pkgs/torrent-ratio/default.nix
