name: Build package
inputs:
  cachix_auth_token:
    description: authToken pass to cachix/cachix-action
    required: true
  debug:
    description: Enable debug
    default: false
  package:
    description: Package to build
    required: true
runs:
  using: composite
  steps:
    - uses: azuwis/actions/nix@main
      with:
        key: package-${{ inputs.package }}
        debug: ${{ github.event_name == 'workflow_dispatch' && inputs.debug }}
    - uses: cachix/cachix-action@3ba601ff5bbb07c7220846facfa2cd81eeee15a1 # v16
      with:
        name: azuwis
        authToken: ${{ inputs.cachix_auth_token }}
    - name: Build
      env:
        PACKAGE: ${{ inputs.package }}
      shell: bash
      run: |
        package=$PACKAGE
        if [ "$(nix eval --impure --json --expr "
        let
          pkgs = import ./pkgs { };
          meta = pkgs.$package.meta;
        in
        (meta ? platforms && builtins.elem builtins.currentSystem meta.platforms)
          || !(meta ? platforms)
        ")" = false ]; then
          echo "::notice::Skip build, wrong platform"
          echo "CACHE_NEED_UPDATE=no" >>"$GITHUB_ENV"
          touch ~/package-skip-build
          exit
        fi
        echo "::group::Build $package"
        nix -L build -f pkgs "$package"
        echo "::endgroup::"
        echo "::group::Install 'tree'"
        nix-env -f '<nixpkgs>' -iA tree
        echo "::endgroup::"
        echo "::group::List files of $package"
        tree -a result
        echo "::endgroup::"
    - uses: azuwis/actions/nix/post@main
    - uses: actions/cache/save@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
      if: ${{ env.CACHE_NEED_UPDATE == 'no' }}
      with:
        key: package-skip-build-${{ inputs.package }}-${{ runner.os }}-${{ runner.arch }}
        path: ~/package-skip-build
